<a href="https://colab.research.google.com/github/FerranBadal/Modelos-de-Regresion-Lineal/blob/main/Actividad_5_(Modelos_de_Regresi%C3%B3n_Lineal).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [ ]:
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

In [ ]:
df= pd.read_csv("cuentas_credicel.csv", encoding= 'latin')
pd.options.display.max_columns = None
df.head(5)

In [ ]:
df.info()

**Convertir columna plazo**

In [9]:
#Eliminar un signo de una columna
df['plazo']=df['plazo'].str.replace('S', '')

In [10]:
#Conversión de tipo de dato de columna de tipo Object a int
df['plazo']= df['plazo'].astype(int)

**Convertir riesgo**

In [11]:
#Sustituyo los strings Atraso, Cancelado y Fraude por la constante "0"
df['riesgo']=df['riesgo'].str.replace('Atraso', '0')
df['riesgo']=df['riesgo'].str.replace('Cancelado', '0')
df['riesgo']=df['riesgo'].str.replace('Fraude', '0')

In [12]:
riesgo_categorias = df.groupby(['riesgo'])['riesgo'].count()
riesgo_categorias

riesgo
-0.05    3
-0.1     6
-0.15    5
-0.2     3
-0.25    7
        ..
9.8      3
9.85     4
9.9      1
9.95     5
91       1
Name: riesgo, Length: 1524, dtype: int64

In [16]:
df["riesgo"]= df["riesgo"].fillna(0)

In [17]:
df["porc_enganche"]=df["porc_enganche"].fillna(method="ffill")

In [ ]:
df.isnull().sum()

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['enganche']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__


**1er Modelo Matemático: y=8.30362837x+928.5596445591957**

In [20]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([928.55964456, 928.55964456, 928.55964456, ..., 928.55964456,
       928.55964456, 928.55964456])

In [24]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.006785706027080618

In [25]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.08237539697677103

In [26]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['precio']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-7.11615993]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 3995.217831233963}

**2do Modelo Matemático: y= -7.11615993x +3995.217831233963**

In [27]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([3995.21783123, 3995.21783123, 3995.21783123, ..., 3995.21783123,
       3995.21783123, 3995.21783123])

In [28]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0006109088972575671

In [29]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.02471657130869019

In [30]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['costo_total']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-18.95458459]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 5694.847880533092}

**3er Modelo Matemático: y=-18.95458459x+5694.847880533092**

In [31]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([5694.84788053, 5694.84788053, 5694.84788053, ..., 5694.84788053,
       5694.84788053, 5694.84788053])

In [32]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.001411319050099502

In [33]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.03756752653688425

In [34]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['pagos_realizados']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-0.03282908]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 10.172388024218485}

**4to Modelo Matemático: y=-0.03282908x +10.172388024218485**

In [35]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([10.17238802, 10.17238802, 10.17238802, ..., 10.17238802,
       10.17238802, 10.17238802])

In [36]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0002557069223527719

In [37]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.015990838700730238

In [38]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['riesgo']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.02461996]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 2.1603808207395727}

**5to Modelo Matemático: y=0.02461996x+2.1603808207395727**

In [39]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([2.16038082, 2.16038082, 2.16038082, ..., 2.16038082, 2.16038082,
       2.16038082])

In [40]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

7.007499711020326e-05

In [41]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.00837108100009809

In [42]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['plazo']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([0.06482148]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 25.926221898296898}

**6to Modelo Matemático: y=0.06482148x+25.926221898296898**

In [44]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([25.9262219, 25.9262219, 25.9262219, ..., 25.9262219, 25.9262219,
       25.9262219])

In [45]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.0009418250456870725

In [46]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.030689168214323968

In [47]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['monto_financiado']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['score_buro'], dtype=object),
 'n_features_in_': 1,
 'coef_': array([-15.3639206]),
 'rank_': 1,
 'singular_': array([713.01781912]),
 'intercept_': 3072.209876915044}

**7mo Modelo Matemático: y=-15.3639206x +3072.209876915044**

In [48]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([3072.20987692, 3072.20987692, 3072.20987692, ..., 3072.20987692,
       3072.20987692, 3072.20987692])

In [49]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.00438865960173207

In [50]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.06624695918857008

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión lineal
Vars_Indep= df[['score_buro']]
Var_Dep= df['porc_enganche']
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

**8vo Modelo Matemático: y=-0.07220764x + 0.8455734321126249**

In [52]:
y_pred= model.predict(X=df[["score_buro"]])
y_pred

array([0.84557343, 0.84557343, 0.84557343, ..., 0.84557343, 0.84557343,
       0.84557343])

In [53]:
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.002932300047172931

In [54]:
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

0.0541507160356438